# Generated by Django 3.2 on 2022-08-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=255)),
                ('cycle', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('validate_in_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_renewal', models.BooleanField(default=False)),
                ('is_upgrade', models.BooleanField(default=False)),
                ('is_downgrade', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='county',
            name='state',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='city',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='county',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='state',
        ),
        migrations.AlterField(
            model_name='firm',
            name='c_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
