# Generated by Django 3.2 on 2022-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('contacts', models.CharField(default='ffffffff', max_length=10)),
                ('matter', models.CharField(default='ffffffff', max_length=10)),
                ('calendar', models.CharField(default='ffffffff', max_length=10)),
                ('flat_fee', models.CharField(default='ffffffff', max_length=10)),
                ('expenses', models.CharField(default='ffffffff', max_length=10)),
                ('trust', models.CharField(default='ffffffff', max_length=10)),
                ('tasks', models.CharField(default='ffffffff', max_length=10)),
                ('invoice', models.CharField(default='ffffffff', max_length=10)),
                ('payments', models.CharField(default='ffffffff', max_length=10)),
                ('full_dob', models.CharField(default='ffffffff', max_length=10)),
                ('full_ssn', models.CharField(default='ffffffff', max_length=10)),
                ('partial_ssn', models.CharField(default='ffffffff', max_length=10)),
                ('partial_dob', models.CharField(default='ffffffff', max_length=10)),
                ('roles', models.CharField(default='ffffffff', max_length=10)),
                ('discounts', models.CharField(default='ffffffff', max_length=10)),
                ('bank_accounts', models.CharField(default='ffffffff', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='bar_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='ext',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='home',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_ext',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='work_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
