# Generated by Django 3.2 on 2022-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_firm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
