# Generated by Django 3.2 on 2022-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220522_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='c_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='p_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='rate',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
