# Generated by Django 3.2 on 2022-05-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220510_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='reports',
            field=models.CharField(default='ffffffff', max_length=10),
        ),
    ]
