# Generated by Django 3.2 on 2022-05-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220526_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='m_name',
            new_name='middle_name',
        ),
    ]
