# Generated by Django 3.2 on 2022-05-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userrole_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='bank_accounts',
            field=models.CharField(default='16_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='calendar',
            field=models.CharField(default='02_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='contacts',
            field=models.CharField(default='00_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='discounts',
            field=models.CharField(default='15_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='expenses',
            field=models.CharField(default='04_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='flat_fee',
            field=models.CharField(default='03_ffffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='full_dob',
            field=models.CharField(default='09_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='full_ssn',
            field=models.CharField(default='10_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='invoice',
            field=models.CharField(default='07_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='matter',
            field=models.CharField(default='01_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='partial_dob',
            field=models.CharField(default='12_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='partial_ssn',
            field=models.CharField(default='11_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='payments',
            field=models.CharField(default='08_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='reports',
            field=models.CharField(default='14_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='roles',
            field=models.CharField(default='13_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='tasks',
            field=models.CharField(default='06_ffffffff', max_length=12),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='trust',
            field=models.CharField(default='05_ffffffff', max_length=12),
        ),
    ]
