# Generated by Django 3.2 on 2022-07-27 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_paymentinfo_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billingAddress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
