# Generated by Django 3.2 on 2022-07-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220727_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmlogo',
            name='firm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='core.firm'),
        ),
        migrations.AlterField(
            model_name='firmlogo',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default_logo.png', null=True, upload_to='firm_logos'),
        ),
    ]
