# Generated by Django 3.2 on 2022-05-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220510_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
