# Generated by Django 3.2 on 2022-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220727_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default_logo.png', null=True, upload_to='firm_logos'),
        ),
        migrations.DeleteModel(
            name='FirmLogo',
        ),
    ]
