# Generated by Django 3.2 on 2022-07-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='role_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
