# Generated by Django 3.2 on 2022-05-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220518_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='role'),
        ),
    ]
