# Generated by Django 3.2 on 2022-05-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_useraccount_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='accounts.role'),
        ),
    ]
